name: Build App
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - 
    name: Install modules
      run: npm install
      working-directory: react-project

    - name: Run tests
      run: npm test
      working-directory: react-project

    - name: Run Build
      run: npm run build
      working-directory: react-project